# Generated by Django 6.0.3 on 2026-04-05 01:01

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tienda', '0002_alter_pelicula_anio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alquiler',
            options={},
        ),
        migrations.RemoveField(
            model_name='alquiler',
            name='precio',
        ),
        migrations.AddField(
            model_name='pelicula',
            name='stock',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tienda.cliente'),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='fecha_alquiler',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='alquiler',
            name='pelicula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='tienda.pelicula'),
        ),
        migrations.AlterField(
            model_name='pelicula',
            name='precio_alquiler',
            field=models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))]),
        ),
    ]
